### ISSUE TITLE
Duplicate column errors

### ISSUE THREAD

**Issue by Helveg** [ppetzold/nestjs-paginate#518]
When running:

```
http://localhost:3000/job-positions?filter.user.id=$eq:bdTlIRyqqner&page=1
```

with

```
paginate(query, this.repo, {
  sortableColumns: [ 'company.name' ],
  searchableColumns: [],
  filterableColumns: { 'user.id': [ '$eq', '$in' ] },
  defaultLimit: 20,
  defaultSortBy: [ [ 'company.name', 'DESC' ] ],
  relations: [ 'user', 'company' ]
})
```

The following error arises:

```
[Nest] 23412  - 03/05/2023, 3:43:26 PM   ERROR [ExceptionsHandler] Duplicate column name 'e_user_id'
QueryFailedError: Duplicate column name 'e_user_id'
```

Inspecting the failed query shows that 2 columns `e_user_id` are generated, one from the filter `user.id` and the other from the column `user_id`:

```
SELECT DISTINCT `distinctAlias`.`e__id` AS `ids_e__id`,
                `distinctAlias`.`e_company_name`
FROM   (SELECT `e`.`_id`                    AS `e__id`,
               `e`.`id`                     AS `e_id`,
               `e`.`freelance`              AS `e_freelance`,
               `e`.`job_title`              AS `e_job_title`,
               `e`.`freelance_client`       AS `e_freelance_client`,
               `e`.`past`                   AS `e_past`,
               `e`.`user_id`                AS `e_user_id`,
               `e`.`company_id`             AS `e_company_id`,
               `e_user`.`_id`               AS `e_user__id`,
               `e_user`.`id`                AS `e_user_id`,
               `e_user`.`auth_subject`      AS `e_user_auth_subject`,
               `e_user`.`name`              AS `e_user_name`,
               `e_user`.`surname`           AS `e_user_surname`,
               `e_user`.`job_title`         AS `e_user_job_title`,
               `e_user`.`email`             AS `e_user_email`,
               `e_user`.`fiscal_code`       AS `e_user_fiscal_code`,
               `e_user`.`calendar_email`    AS `e_user_calendar_email`,
               `e_user`.`signup_date`       AS `e_user_signup_date`,
               `e_user`.`phone_number`      AS `e_user_phone_number`,
               `e_user`.`points`            AS `e_user_points`,
               `e_user`.`seniority`         AS `e_user_seniority`,
               `e_user`.`nation`            AS `e_user_nation`,
               `e_user`.`city`              AS `e_user_city`,
               `e_user`.`contactpreference` AS `e_user_contactPreference`,
               `e_user`.`freelancer`        AS `e_user_freelancer`,
               `e_user`.`corporate_worker`  AS `e_user_corporate_worker`,
               `e_user`.`platform_id`       AS `e_user_platform_id`,
               `e_user`.`role_id`           AS `e_user_role_id`,
               `e_company`.`_id`            AS `e_company__id`,
               `e_company`.`id`             AS `e_company_id`,
               `e_company`.`name`           AS `e_company_name`
        FROM   `job_position` `e`
               LEFT JOIN `user` `e_user`
                      ON `e_user`.`_id` = `e`.`user_id`
               LEFT JOIN `company` `e_company`
                      ON `e_company`.`_id` = `e`.`company_id`
        WHERE  ( `e_user`.`id` = ? )) `distinctAlias`
ORDER  BY `distinctAlias`.`e_company_name` DESC,
          `e__id` ASC
LIMIT  1 
```

Is this a user or library error? If it's a user error, how can I resolve it, and what can we do to catch this beforehand to raise a better error?

**Comment by Helveg** [comment]
I never noticed this before because the problem does not seem to be a problem when using the SQLite driver:

```
SELECT DISTINCT "distinctAlias"."e__id" AS "ids_e__id",
                "distinctAlias"."e_company_name"
FROM   (SELECT "e"."_id"                    AS "e__id",
               "e"."id"                     AS "e_id",
               "e"."freelance"              AS "e_freelance",
               "e"."job_title"              AS "e_job_title",
               "e"."freelance_client"       AS "e_freelance_client",
               "e"."past"                   AS "e_past",
               "e"."user_id"                AS "e_user_id",
               "e"."company_id"             AS "e_company_id",
               "e_user"."_id"               AS "e_user__id",
               "e_user"."id"                AS "e_user_id",
               "e_user"."auth_subject"      AS "e_user_auth_subject",
               "e_user"."name"              AS "e_user_name",
               "e_user"."surname"           AS "e_user_surname",
               "e_user"."job_title"         AS "e_user_job_title",
               "e_user"."email"             AS "e_user_email",
               "e_user"."fiscal_code"       AS "e_user_fiscal_code",
               "e_user"."calendar_email"    AS "e_user_calendar_email",
               "e_user"."signup_date"       AS "e_user_signup_date",
               "e_user"."phone_number"      AS "e_user_phone_number",
               "e_user"."points"            AS "e_user_points",
               "e_user"."seniority"         AS "e_user_seniority",
               "e_user"."nation"            AS "e_user_nation",
               "e_user"."city"              AS "e_user_city",
               "e_user"."contactpreference" AS "e_user_contactPreference",
               "e_user"."freelancer"        AS "e_user_freelancer",
               "e_user"."corporate_worker"  AS "e_user_corporate_worker",
               "e_user"."platform_id"       AS "e_user_platform_id",
               "e_user"."role_id"           AS "e_user_role_id",
               "e_company"."_id"            AS "e_company__id",
               "e_company"."id"             AS "e_company_id",
               "e_company"."name"           AS "e_company_name"
        FROM   "job_position" "e"
               LEFT JOIN "user" "e_user"
                      ON "e_user"."_id" = "e"."user_id"
               LEFT JOIN "company" "e_company"
                      ON "e_company"."_id" = "e"."company_id"
        WHERE  ( "e_user"."id" = ? )) "distinctAlias"
ORDER  BY "distinctAlias"."e_company_name" DESC,
          "e__id" ASC
LIMIT  20
```

works as expected

**Comment by ppetzold** [comment]
What's the other driver? postgres?

**Comment by Helveg** [comment]
MySQL! Sorry :)

**Comment by ppetzold** [comment]
Yep. really should have coverage of some additional driver in CI to catch those issues beforehand. will try to get #486 merged for starters

**Comment by Helveg** [comment]
This is currently blocking the release of our product, are there any workarounds you can suggest that may work on my own fork of this project?

**Comment by ppetzold** [comment]
does downgrading to v4.6.4 work?

**Comment by Helveg** [comment]
It appears to occur there as well, even as far back as 4.0.0

**Comment by Helveg** [comment]
So a few notes: splicing in an arbitrary tag for relationship aliases seems to work well. You do stumble upon "unknown column" errors because `filter.ts:addWhereCondition` uses alias's that aren't available at that point. 

When using filters in MySQL the `addFilter` > `addWhereCondition` uses `fixColumnAlias`, and in general seems to generate aliases that are created in the same `SELECT` block, which is a syntactical error. MySQL `WHERE` clauses can only refer to aliases of a subquery. I then patched a patch on top of my patch that replaces `${rel}_tag_${relcol}` with `${rel}_tag.${relcol}`, which does work, because `${rel}_tag` is the name of the left joined relationship.

**Comment by ppetzold** [comment]
sorry, didn't have time yet to look more into it. but have you tried `PaginationType.LIMIT_AND_OFFSET`?

afaik it doesn't create this weird sub query but may introduce side effects due to typeorm bug.

**Comment by Helveg** [comment]
With v6.1 and MySQL the generated queries run into "full group by" errors, which I can solve by changing my SQL_MODE system variable, but will be a hoop to jump through for new users:

```
[Nest] 21268  - 03/20/2023, 2:56:50 PM   ERROR [ExceptionsHandler] Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'buddee.user._id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
QueryFailedError: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'buddee.user._id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at Query.onResult (C:\Users\pwd06\git\buddee-back-end\src\driver\mysql\MysqlQueryRunner.ts:222:33)
    at Query.execute (C:\Users\pwd06\git\buddee-back-end\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (C:\Users\pwd06\git\buddee-back-end\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\Users\pwd06\git\buddee-back-end\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\Users\pwd06\git\buddee-back-end\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\pwd06\git\buddee-back-end\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

When I was patching I already ran into these, but couldn't figure out from online sources, nor had enough time, to maybe change the generated selects/group-bys to avoid this error entirely.

**Comment by ppetzold** [comment]
hmm, okay. I think I will add mysql test run then. just made everything pass for postgres with v7. let's see what else comes up for mysql

**Comment by Helveg** [comment]
The column collisions are fixed though 🎉

**Comment by juventus18** [comment]
It seems to work in 4.7.0. I am also using MySQL driver. I was having the problem around the time 4.7.0 came out and I upgraded to fix it. I recently ran an `npm update` and this got bumped up to 4.14.0 and broke again. 

I think there are some things going around with TypeORM having problems as well. I started looking into it a bit just hours before 4.7.0 of this library (pure chance). I was in this discussion about it: https://github.com/typeorm/typeorm/issues/6852#issuecomment-1409553631 (and another comment below)

I ended up reverting to 4.7.0 for now, back working. 

relevant package.json (currently working)
```
"nestjs-paginate": "^4.7.0",
"typeorm": "^0.3.14",
"typeorm-naming-strategies": "^4.1.0"
```

Not exactly sure if the naming strategies are relevant, however, seems it might be... The only strategy available is snake_case which is the joining character TypeORM and nestjs-paginate (i.e. https://github.com/ppetzold/nestjs-paginate/blob/c2c6eaf44eb8506f1a378cefe9b07624bb0d292b/src/helper.ts#L97). Stock TypeORM, with CamelCase might not be affected.

Hope this helps...

**Comment by ppetzold** [comment]
Have you tried paginationType limit/offset in config?

**Comment by Helveg** [comment]
@ppetzold We're back once again. This query is generated for 8.1.2:

```
SELECT 
  DISTINCT `distinctAlias`.`user__id` AS `ids_user__id`, 
  `distinctAlias`.`user_signup_date` 
FROM 
  (
    SELECT 
      `user`.`_id` AS `user__id`, 
      `user`.`id` AS `user_id`, 
      `user`.`auth_subject` AS `user_auth_subject`, 
      `user`.`name` AS `user_name`, 
      `user`.`surname` AS `user_surname`, 
      `user`.`job_title` AS `user_job_title`, 
      `user`.`email` AS `user_email`, 
      `user`.`fiscal_code` AS `user_fiscal_code`, 
      `user`.`calendar_email` AS `user_calendar_email`, 
      `user`.`signup_date` AS `user_signup_date`, 
      `user`.`phone_number` AS `user_phone_number`, 
      `user`.`points` AS `user_points`, 
      `user`.`seniority` AS `user_seniority`, 
      `user`.`nation` AS `user_nation`, 
      `user`.`city` AS `user_city`, 
      `user`.`contactPreference` AS `user_contactPreference`, 
      `user`.`freelancer` AS `user_freelancer`, 
      `user`.`corporate_worker` AS `user_corporate_worker`, 
      `user`.`platform_id` AS `user_platform_id`, 
      `user`.`role_id` AS `user_role_id`, 
      `user_role`.`_id` AS `user_role__id`, 
      `user_role`.`id` AS `user_role_id`, 
      `user_role`.`name` AS `user_role_name`, 
      `user_role`.`description` AS `user_role_description`, 
      `user_role`.`platform_id` AS `user_role_platform_id`, 
      `user_degrees`.`_id` AS `user_degrees__id`, 
      `user_degrees`.`id` AS `user_degrees_id`, 
      `user_degrees`.`name` AS `user_degrees_name`, 
      `user_degrees`.`type` AS `user_degrees_type`, 
      `user_degrees`.`description` AS `user_degrees_description`, 
      `user_degrees`.`department_id` AS `user_degrees_department_id`, 
      `user_degrees`.`parent_degree_id` AS `user_degrees_parent_degree_id`, 
      `user_businessFunctions`.`_id` AS `user_businessFunctions__id`, 
      `user_businessFunctions`.`id` AS `user_businessFunctions_id`, 
      `user_businessFunctions`.`category` AS `user_businessFunctions_category`, 
      `user_businessFunctions`.`name` AS `user_businessFunctions_name`, 
      `user_industries`.`_id` AS `user_industries__id`, 
      `user_industries`.`id` AS `user_industries_id`, 
      `user_industries`.`name` AS `user_industries_name`, 
      `user_industries`.`category` AS `user_industries_category`, 
      `user_jobPositions`.`_id` AS `user_jobPositions__id`, 
      `user_jobPositions`.`id` AS `user_jobPositions_id`, 
      `user_jobPositions`.`freelance` AS `user_jobPositions_freelance`, 
      `user_jobPositions`.`job_title` AS `user_jobPositions_job_title`, 
      `user_jobPositions`.`freelance_client` AS `user_jobPositions_freelance_client`, 
      `user_jobPositions`.`past` AS `user_jobPositions_past`, 
      `user_jobPositions`.`user_id` AS `user_jobPositions_user_id`, 
      `user_jobPositions`.`company_id` AS `user_jobPositions_company_id`, 
      `user_wishlistCompanies`.`_id` AS `user_wishlistCompanies__id`, 
      `user_wishlistCompanies`.`id` AS `user_wishlistCompanies_id`, 
      `user_wishlistCompanies`.`name` AS `user_wishlistCompanies_name`, 
      `user_wishlistCompanies`.`VAT` AS `user_wishlistCompanies_VAT`, 
      `user_wishlistCompanies`.`parent_company` AS `user_wishlistCompanies_parent_company`, 
      `user_wishlistCompanies`.`group` AS `user_wishlistCompanies_group`, 
      `user_wishlistCompanies`.`registered_office_city` AS `user_wishlistCompanies_registered_office_city`, 
      `user_wishlistCompanies`.`creation_date` AS `user_wishlistCompanies_creation_date` 
    FROM 
      `user` `user` 
      LEFT JOIN `followers` `following_user` ON `following_user`.`following_id` = `user`.`_id` 
      LEFT JOIN `user` `following` ON `following`.`_id` = `following_user`.`follower_id` 
      LEFT JOIN `followers` `user_follower` ON `user_follower`.`follower_id` = `user`.`_id` 
      LEFT JOIN `user` `follower` ON `follower`.`_id` = `user_follower`.`following_id` 
      LEFT JOIN `role` `user_role` ON `user_role`.`_id` = `user`.`role_id` 
      LEFT JOIN `users_degrees` `user_user_degrees` ON `user_user_degrees`.`user_id` = `user`.`_id` 
      LEFT JOIN `degree` `user_degrees` ON `user_degrees`.`_id` = `user_user_degrees`.`degree_id` 
      LEFT JOIN `user_business_functions` `user_user_businessFunctions` ON `user_user_businessFunctions`.`user_id` = `user`.`_id` 
      LEFT JOIN `business_function` `user_businessFunctions` ON `user_businessFunctions`.`_id` = `user_user_businessFunctions`.`businessFunction_id` 
      LEFT JOIN `user_industries_industry` `user_user_industries` ON `user_user_industries`.`user_id` = `user`.`_id` 
      LEFT JOIN `industry` `user_industries` ON `user_industries`.`_id` = `user_user_industries`.`industry_id` 
      LEFT JOIN `job_position` `user_jobPositions` ON `user_jobPositions`.`user_id` = `user`.`_id` 
      LEFT JOIN `user_wishlist_companies` `user_user_wishlistCompanies` ON `user_user_wishlistCompanies`.`user_id` = `user`.`_id` 
      LEFT JOIN `company` `user_wishlistCompanies` ON `user_wishlistCompanies`.`_id` = `user_user_wishlistCompanies`.`company_id` 
    WHERE 
      `following`.`id` = ? 
      OR `follower`.`id` = ?
  ) `distinctAlias` 
ORDER BY 
  `distinctAlias`.`user_signup_date` DESC, 
  `user__id` ASC 
LIMIT 
  20
```

Same type of collision occurs: `user.role_id` and `user_role.id`. Is this covered by tests? I suppose to reproduce it all you need is a relationship with on the owning side a column name that resolves to a selected column on the related table:

```
@Entity()
class Thing {
  @PrimaryGeneratedColumn()
  _not_id: number;

  @Column()
  id: string
}
  
@Entity()
class Parent {
  @PrimaryGeneratedColumn()
  _not_id: number;

  @OneToOne()
  @JoinColumn()
  thing: Thing
}

When `paginate` includes `{relations: ['thing']}` it should lead to a collision between `parent.thing_id` and `parent_thing.id`

**Comment by Helveg** [comment]
```
SELECT 
  DISTINCT `distinctAlias`.`user__id` AS `ids_user__id`, 
  `distinctAlias`.`user_signup_date` 
FROM 
  (
    SELECT 
      `user`.`_id` AS `user__id`, 
      `user`.`id` AS `user_id`, 
      `user`.`auth_subject` AS `user_auth_subject`, 
      `user`.`name` AS `user_name`, 
      `user`.`surname` AS `user_surname`, 
      `user`.`job_title` AS `user_job_title`, 
      `user`.`email` AS `user_email`, 
      `user`.`fiscal_code` AS `user_fiscal_code`, 
      `user`.`calendar_email` AS `user_calendar_email`, 
      `user`.`signup_date` AS `user_signup_date`, 
      `user`.`phone_number` AS `user_phone_number`, 
      `user`.`points` AS `user_points`, 
      `user`.`seniority` AS `user_seniority`, 
      `user`.`nation` AS `user_nation`, 
      `user`.`city` AS `user_city`, 
      `user`.`contactPreference` AS `user_contactPreference`, 
      `user`.`freelancer` AS `user_freelancer`, 
      `user`.`corporate_worker` AS `user_corporate_worker`, 
      `user`.`platform_id` AS `user_platform_id`, 
      `user`.`role_id` AS `user_role_id`, 
      `user_role`.`_id` AS `user_role__id`, 
      `user_role`.`id` AS `user_role_id`, 
      `user_role`.`name` AS `user_role_name`, 
      `user_role`.`description` AS `user_role_description`, 
      `user_role`.`platform_id` AS `user_role_platform_id`, 
      `user_degrees`.`_id` AS `user_degrees__id`, 
      `user_degrees`.`id` AS `user_degrees_id`, 
      `user_degrees`.`name` AS `user_degrees_name`, 
      `user_degrees`.`type` AS `user_degrees_type`, 
      `user_degrees`.`description` AS `user_degrees_description`, 
      `user_degrees`.`department_id` AS `user_degrees_department_id`, 
      `user_degrees`.`parent_degree_id` AS `user_degrees_parent_degree_id`, 
      `user_businessFunctions`.`_id` AS `user_businessFunctions__id`, 
      `user_businessFunctions`.`id` AS `user_businessFunctions_id`, 
      `user_businessFunctions`.`category` AS `user_businessFunctions_category`, 
      `user_businessFunctions`.`name` AS `user_businessFunctions_name`, 
      `user_industries`.`_id` AS `user_industries__id`, 
      `user_industries`.`id` AS `user_industries_id`, 
      `user_industries`.`name` AS `user_industries_name`, 
      `user_industries`.`category` AS `user_industries_category`, 
      `user_jobPositions`.`_id` AS `user_jobPositions__id`, 
      `user_jobPositions`.`id` AS `user_jobPositions_id`, 
      `user_jobPositions`.`freelance` AS `user_jobPositions_freelance`, 
      `user_jobPositions`.`job_title` AS `user_jobPositions_job_title`, 
      `user_jobPositions`.`freelance_client` AS `user_jobPositions_freelance_client`, 
      `user_jobPositions`.`past` AS `user_jobPositions_past`, 
      `user_jobPositions`.`user_id` AS `user_jobPositions_user_id`, 
      `user_jobPositions`.`company_id` AS `user_jobPositions_company_id`, 
      `user_wishlistCompanies`.`_id` AS `user_wishlistCompanies__id`, 
      `user_wishlistCompanies`.`id` AS `user_wishlistCompanies_id`, 
      `user_wishlistCompanies`.`name` AS `user_wishlistCompanies_name`, 
      `user_wishlistCompanies`.`VAT` AS `user_wishlistCompanies_VAT`, 
      `user_wishlistCompanies`.`parent_company` AS `user_wishlistCompanies_parent_company`, 
      `user_wishlistCompanies`.`group` AS `user_wishlistCompanies_group`, 
      `user_wishlistCompanies`.`registered_office_city` AS `user_wishlistCompanies_registered_office_city`, 
      `user_wishlistCompanies`.`creation_date` AS `user_wishlistCompanies_creation_date` 
    FROM 
      `user` `user` 
      LEFT JOIN `followers` `following_user` ON `following_user`.`following_id` = `user`.`_id` 
      LEFT JOIN `user` `following` ON `following`.`_id` = `following_user`.`follower_id` 
      LEFT JOIN `followers` `user_follower` ON `user_follower`.`follower_id` = `user`.`_id` 
      LEFT JOIN `user` `follower` ON `follower`.`_id` = `user_follower`.`following_id` 
      LEFT JOIN `role` `user_role` ON `user_role`.`_id` = `user`.`role_id` 
      LEFT JOIN `users_degrees` `user_user_degrees` ON `user_user_degrees`.`user_id` = `user`.`_id` 
      LEFT JOIN `degree` `user_degrees` ON `user_degrees`.`_id` = `user_user_degrees`.`degree_id` 
      LEFT JOIN `user_business_functions` `user_user_businessFunctions` ON `user_user_businessFunctions`.`user_id` = `user`.`_id` 
      LEFT JOIN `business_function` `user_businessFunctions` ON `user_businessFunctions`.`_id` = `user_user_businessFunctions`.`businessFunction_id` 
      LEFT JOIN `user_industries_industry` `user_user_industries` ON `user_user_industries`.`user_id` = `user`.`_id` 
      LEFT JOIN `industry` `user_industries` ON `user_industries`.`_id` = `user_user_industries`.`industry_id` 
      LEFT JOIN `job_position` `user_jobPositions` ON `user_jobPositions`.`user_id` = `user`.`_id` 
      LEFT JOIN `user_wishlist_companies` `user_user_wishlistCompanies` ON `user_user_wishlistCompanies`.`user_id` = `user`.`_id` 
      LEFT JOIN `company` `user_wishlistCompanies` ON `user_wishlistCompanies`.`_id` = `user_user_wishlistCompanies`.`company_id` 
    WHERE 
      `following`.`id` = ? 
      OR `follower`.`id` = ?
  ) `distinctAlias` 
ORDER BY 
  `distinctAlias`.`user_signup_date` DESC, 
  `user__id` ASC 
LIMIT 
  20
```

**Comment by Helveg** [comment]
Fixed by my PR
