### ISSUE TITLE
Cannot mock queryBuilder in unit tests

### ISSUE THREAD

**Issue by Mnigos** [ppetzold/nestjs-paginate#663]
```ts

  ● MessagesService › should find all messages

    TypeError: queryBuilder.take is not a function

      10 |
      11 |   async findAll(query: PaginateQuery) {
    > 12 |     return paginate(query, this.messageRepository, {
         |                    ^
      13 |       sortableColumns: ['id'],
      14 |       defaultSortBy: [['id', 'DESC']],
      15 |       searchableColumns: ['query', 'response'],

      at paginate (node_modules/nestjs-paginate/src/paginate.ts:121:26)
      at MessagesService.findAll (src/modules/messages/messages.service.ts:12:20)
      at Object.<anonymous> (src/modules/messages/messages.service.spec.ts:48:49)
```
      
      
 ```ts
  beforeEach(async () => {
  const module: TestingModule = await Test.createTestingModule({
    providers: [
      MessagesService,
      {
        provide: MessageRepository,
        useValue: {
          findMessages: jest.fn(),
          findMessagesById: jest.fn(),
          createMessage: jest.fn(),
          queryBuilder: () => ({
            take: jest.fn().mockReturnThis(),
          }),
        },
      },
    ],
  }).compile()

  messagesService = module.get<MessagesService>(MessagesService)
  messageRepository = module.get<MessageRepository>(MessageRepository)
})
```

```ts
   it('should find all messages', async () => {
    const paginateQueryMock = createMock<PaginateQuery>()
    const messagesMock = [createMock<Message>(), createMock<Message>()]

    const findMessagesSpy = jest
      .spyOn(messageRepository, 'findMessages')
      .mockResolvedValue(messagesMock)

    const foundMessages = await messagesService.findAll(paginateQueryMock)

    expect(foundMessages).toEqual(messagesMock)
    expect(findMessagesSpy).toHaveBeenCalled()
  })
  ```

**Comment by ppetzold** [comment]
repo uses `createQueryBuilder()`

https://github.com/ppetzold/nestjs-paginate/blob/master/src/paginate.ts#L107
